default_platform(:ios)

platform :ios do
    desc "Release to appstore"
    lane :release do
        ensure_git_status_clean
        add_git_tag(tag: "#{get_version_number_from_xcodeproj}-#{get_build_number_from_xcodeproj}")
        build_app(scheme: "Habbitio", xcargs: "-allowProvisioningUpdates")
        upload_to_app_store(force: true, skip_screenshots: true, skip_metadata: true)
        clean_build_artifacts
        increment_build_number_in_xcodeproj
        git_add
        git_commit(path: "*/*", message: "Build Number Bump #{get_version_number_from_xcodeproj}-#{get_build_number_from_xcodeproj}")
    end

    desc "Set version number"
    lane :set_version do |options|
        version_number = options[:version]
        if version_number.nil? || version_number.to_s == ""
            throw "Required version_number parameter"
        end
	increment_version_number_in_xcodeproj(version_number: version_number)
	increment_build_number_in_xcodeproj(build_number: "1")
	git_add
	git_commit(path: "*/*", message: "Version Bump #{get_version_number_from_xcodeproj}")
    end
end
